# Generated by Django 4.2.1 on 2023-09-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='بيانات_النادي',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نوع_النادي', models.CharField(choices=[('نادي_عام', 'نادي_عام'), ('نادي_خاص', 'نادي_خاص')], max_length=255)),
                ('اسم_النادي', models.CharField(max_length=255)),
                ('تخصص_النادي', models.CharField(max_length=1000)),
                ('فكرة_النادي', models.CharField(max_length=1000)),
                ('رسالة_النادي', models.CharField(max_length=1000)),
                ('رؤية_النادي', models.CharField(max_length=1000)),
                ('أهداف_النادي', models.CharField(max_length=1000)),
                ('الطلبة', models.BooleanField(default=False)),
                ('الشركات', models.BooleanField(default=False)),
                ('المنشآت_العمومية', models.BooleanField(default=False)),
                ('الطلبة_من_خارج_المؤسسة', models.BooleanField(default=False)),
                ('الصّناعيين', models.BooleanField(default=False)),
                ('الدواوين', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='مطلب_نشاط',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نشاط_عدد', models.CharField(max_length=255)),
                ('تاريخ_بداية_النشاط', models.DateField()),
                ('تاريخ_نهاية_النشاط', models.DateField()),
                ('الزمان', models.TimeField()),
                ('المكان', models.CharField(max_length=1000)),
                ('الموضوع', models.CharField(max_length=1000)),
                ('رئيس_النادي', models.CharField(max_length=255)),
                ('اسم_النادي', models.CharField(max_length=255)),
                ('يوم_مفتوح', models.BooleanField(default=False)),
                ('طلب_دعم', models.BooleanField(default=False)),
                ('نشاط_ثقافي', models.BooleanField(default=False)),
                ('رحلة_دراسية', models.BooleanField(default=False)),
                ('نشاط_رياضي', models.BooleanField(default=False)),
                ('نشاط_علمي', models.BooleanField(default=False)),
                ('رحلة_ترفيهية', models.BooleanField(default=False)),
                ('الفئة_المستهدفة', models.CharField(choices=[('طلبة من داخل المعهد', 'طلبة من داخل المعهد'), ('طلبة من داخل و خارج المعهد', 'طلبة من داخل و خارج المعهد'), ('كل الفئات', 'كل الفئات')], max_length=255)),
                ('نبذة_عن_النشاط', models.CharField(max_length=2000)),
                ('النادي', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubapp.بيانات_النادي')),
            ],
        ),
        migrations.CreateModel(
            name='مطلب_حجز_قاعة',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('القاعة', models.CharField(choices=[('قاعة ملتقيات الإدارة', 'قاعة ملتقيات الإدارة'), ('قاعة ملتقيات الطلبة', 'قاعة ملتقيات الطلبة'), ('قاعة 4', 'قاعة 4'), ('قاعة قسم', 'قاعة قسم'), ('المكتبة', 'المكتبة'), ('Amphi', 'Amphi'), ('Amphi Théâtre', 'Amphi Théâtre')], max_length=255)),
                ('اسم_و_لقب_رئيس_النادي_أو_المنظمة', models.CharField(max_length=255)),
                ('الموضوع', models.CharField(max_length=1000)),
                ('تحديد_اليوم_و_التوقيت', models.DateTimeField()),
                ('ادارة_النشاط_الثقافي', models.CharField(max_length=255)),
                ('اسم_الاستاذ_المشرف', models.CharField(max_length=255)),
                ('رقم_الهاتف', models.CharField(max_length=20)),
                ('اليوم', models.DateField()),
                ('اسم_النادي_أو_المنظمة', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clubapp.بيانات_النادي')),
            ],
        ),
    ]
