# Generated by Django 4.2.1 on 2023-10-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='مطلب_حجز_قاعة',
            name='رقم_الهاتف',
            field=models.CharField(max_length=8),
        ),
    ]
