# Generated by Django 4.2.1 on 2023-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_alter_مطلب_حجز_قاعة_رقم_الهاتف'),
    ]

    operations = [
        migrations.AlterField(
            model_name='مطلب_حجز_قاعة',
            name='رقم_الهاتف',
            field=models.IntegerField(max_length=8),
        ),
    ]
