# Generated by Django 4.2.1 on 2023-10-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0004_alter_مطلب_حجز_قاعة_رقم_الهاتف'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='مطلب_حجز_قاعة',
            name='اليوم',
        ),
    ]
