# Generated by Django 4.2.5 on 2023-10-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_remove_مطلب_حجز_قاعة_اليوم'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='اسم_النادي',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='رحلة_ترفيهية',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='رحلة_دراسية',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='طلب_دعم',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='نشاط_ثقافي',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='نشاط_رياضي',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='نشاط_علمي',
        ),
        migrations.RemoveField(
            model_name='مطلب_نشاط',
            name='يوم_مفتوح',
        ),
        migrations.AddField(
            model_name='مطلب_نشاط',
            name='نوع_النشاط',
            field=models.CharField(choices=[('يوم مفتوح', 'يوم مفتوح'), ('طلب دعم', 'طلب دعم'), ('رحلة دراسية', 'رحلة دراسية'), ('نشاط ثقافي', 'نشاط ثقافي'), ('نشاط رياضي', 'نشاط رياضي'), ('نشاط علمي', 'نشاط علمي'), ('رحلة ترفيهية', 'رحلة ترفيهية')], default='نشاط ثقافي', max_length=255),
        ),
    ]
