# Generated by Django 4.2.1 on 2023-10-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0005_remove_مطلب_حجز_قاعة_اليوم'),
    ]

    operations = [
        migrations.RenameField(
            model_name='مطلب_حجز_قاعة',
            old_name='تحديد_اليوم_و_التوقيت',
            new_name='اليوم_و_التوقيت',
        ),
    ]
